[package]
name = "someip_parse"
version = "0.3.1"
authors = ["Julian Schmid <info@julianschmid.name>"]
description = "A library for parsing the SOME/IP network protocol (without payload interpretation)."
repository = "https://github.com/JulianSchmid/someip-parse-rs"
categories = ["network-programming", "parser-implementations"]
keywords = ["someip", "autosar"]
license = "BSD-3-Clause"
readme = "README.md"
exclude = [
    ".gitignore",
    ".travis.yml",
    ".github/*",
    ".gitlab-ci.yml",
    ".travis/*",
    "appveyor.yml"
]

[dependencies]

[dev-dependencies]
assert_matches = "1.5.0"
etherparse = "0.9.0"
proptest = "1.0.0"
clap = "2.33.3"
rpcap = "0.3.0"
time = "0.3.1"
