name: codecoverage 

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  codecoverage_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        override: true
        components: llvm-tools-preview
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-binutils rustfilt
    - name: Install jq
      run: sudo apt install jq
    - name: Determine coverage
      run: coverage/coverage.bash
      shell: bash
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        files: target/coverage/export.lcov.txt
